safe: true
auto: true
server: true
markdown: redcarpet
pygments: false
future: true
lsi: false
permalink: pretty

redcarpet:
    extensions: [smart, no_intra_emphasis, fenced_code_blocks, autolink, strikethrough]
